logging:
  level:
    root: info
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  servlet-path: /spring
