logging:
  level:
    root: debug
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log

server:
  servlet-path: /spring

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    #preferIpAddress: true
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
