server:
  port: 9292

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/magnesium

---
spring:
  profiles: uat
  data:
    mongodb:
      uri: mongodb://UAT-DB:27017/magnesium

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://PROD-DB:27017/magnesium
